[project]
name = "python-agent-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "borderf", email = "15653771198@163.com" }]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
python-agent-lab = "python_agent_lab:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
